In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf
import io
from google.colab import files
uploaded = files.upload()

Saving bank_telemarketing.csv to bank_telemarketing.csv

In [2]:
tele_df = pd.read_csv(io.BytesIO(uploaded['bank_telemarketing.csv']))
tele_df.head()

,Age,Job,Marital_Status,Education,Default_Credit,Housing_Loan,Personal_Loan,Subscribed
0,56,other,married,Primary_Education,no,no,no,no
1,37,services,married,Secondary_Education,no,yes,no,no
2,40,admin,married,Primary_Education,no,no,no,no
3,56,services,married,Secondary_Education,no,no,yes,no
4,59,admin,married,Professional_Education,no,no,no,no

In [3]:
# Generate our categorical variable list
tele_cat = tele_df.dtypes[tele_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
tele_df[tele_cat].nunique()

Job               9
Marital_Status    3
Education         4
Default_Credit    2
Housing_Loan      2
Personal_Loan     2
Subscribed        2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(tele_df[tele_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(tele_cat)
encode_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,Marital_Status_divorced,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
tele_df = tele_df.merge(encode_df,left_index=True, right_index=True)
tele_df = tele_df.drop(tele_cat,1)
tele_df.head()

<ipython-input-5-32f23930b0f3>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  tele_df = tele_df.drop(tele_cat,1)

,Age,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,56,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,40,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,59,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [6]:
# Remove loan status target from features data
y = tele_df.Subscribed_yes.values
X = tele_df.drop(columns=["Subscribed_no","Subscribed_yes"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
# Create the SVM model
svm = SVC(kernel='linear')

In [8]:
# Train the model
svm.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
# Evaluate the model
y_pred = svm.predict(X_test_scaled)
print(f" SVM model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 SVM model accuracy: 0.873

In [10]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [11]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
715/715 [==============================] - 2s 2ms/step - loss: 0.4331 - accuracy: 0.8332
Epoch 2/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3734 - accuracy: 0.8734
Epoch 3/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3710 - accuracy: 0.8736
Epoch 4/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3696 - accuracy: 0.8735
Epoch 5/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3683 - accuracy: 0.8735
Epoch 6/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3675 - accuracy: 0.8734
Epoch 7/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3668 - accuracy: 0.8735
Epoch 8/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3661 - accuracy: 0.8734
Epoch 9/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3656 - accuracy: 0.8735
Epoch 10/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3653 - accuracy: 0.8732
Epoch 11/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3648 - accuracy: 0.8733
Epoch 12/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3644 - accuracy: 0.8735
Epoch 13/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3641 - accuracy: 0.8736
Epoch 14/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3640 - accuracy: 0.8735
Epoch 15/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3637 - accuracy: 0.8734
Epoch 16/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3635 - accuracy: 0.8733
Epoch 17/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3634 - accuracy: 0.8739
Epoch 18/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3634 - accuracy: 0.8739
Epoch 19/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3634 - accuracy: 0.8736
Epoch 20/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3634 - accuracy: 0.8738
Epoch 21/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3633 - accuracy: 0.8736
Epoch 22/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3633 - accuracy: 0.8736
Epoch 23/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8737
Epoch 24/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3631 - accuracy: 0.8737
Epoch 25/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8734
Epoch 26/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3625 - accuracy: 0.8739
Epoch 27/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3627 - accuracy: 0.8736
Epoch 28/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8741
Epoch 29/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3626 - accuracy: 0.8735
Epoch 30/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3628 - accuracy: 0.8739
Epoch 31/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3627 - accuracy: 0.8738
Epoch 32/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3628 - accuracy: 0.8738
Epoch 33/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3624 - accuracy: 0.8741
Epoch 34/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3624 - accuracy: 0.8736
Epoch 35/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3625 - accuracy: 0.8739
Epoch 36/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3625 - accuracy: 0.8738
Epoch 37/50
715/715 [==============================] - 2s 2ms/step - loss: 0.3623 - accuracy: 0.8740
Epoch 38/50
715/715 [==============================] - 2s 3ms/step - loss: 0.3623 - accuracy: 0.8740
Epoch 39/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3624 - accuracy: 0.8740
Epoch 40/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3623 - accuracy: 0.8734
Epoch 41/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8740
Epoch 42/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8738
Epoch 43/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3621 - accuracy: 0.8740
Epoch 44/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8738
Epoch 45/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3621 - accuracy: 0.8736
Epoch 46/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3623 - accuracy: 0.8740
Epoch 47/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8737
Epoch 48/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8739
Epoch 49/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8740
Epoch 50/50
715/715 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8737
239/239 - 0s - loss: 0.3672 - accuracy: 0.8728 - 388ms/epoch - 2ms/step
Loss: 0.36722004413604736, Accuracy: 0.8728346228599548