In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
import io
from google.colab import files
uploaded = files.upload()

Saving HR-Employee-Attrition.csv to HR-Employee-Attrition.csv

In [10]:
attrition_df = pd.read_csv(io.BytesIO(uploaded['HR-Employee-Attrition.csv']))

In [11]:
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [13]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [14]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [15]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

<ipython-input-15-69eb5d29ad8d>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  attrition_df = attrition_df.drop(attrition_cat,1)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [16]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

<ipython-input-16-c667c5b6ef01>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

In [17]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [19]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 1s 3ms/step - loss: 311.3519 - accuracy: 0.8094
Epoch 2/100
35/35 [==============================] - 0s 2ms/step - loss: 79.8260 - accuracy: 0.7659
Epoch 3/100
35/35 [==============================] - 0s 2ms/step - loss: 6.5930 - accuracy: 0.3748
Epoch 4/100
35/35 [==============================] - 0s 2ms/step - loss: 4.0745 - accuracy: 0.5299
Epoch 5/100
35/35 [==============================] - 0s 2ms/step - loss: 3.3958 - accuracy: 0.8176
Epoch 6/100
35/35 [==============================] - 0s 2ms/step - loss: 2.9954 - accuracy: 0.8167
Epoch 7/100
35/35 [==============================] - 0s 2ms/step - loss: 2.3042 - accuracy: 0.8203
Epoch 8/100
35/35 [==============================] - 0s 2ms/step - loss: 2.1420 - accuracy: 0.8176
Epoch 9/100
35/35 [==============================] - 0s 2ms/step - loss: 2.2589 - accuracy: 0.8221
Epoch 10/100
35/35 [==============================] - 0s 2ms/step - loss: 1.7789 - accuracy: 0.8176
Epoch 11/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6461 - accuracy: 0.8194
Epoch 12/100
35/35 [==============================] - 0s 3ms/step - loss: 1.5423 - accuracy: 0.8176
Epoch 13/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5340 - accuracy: 0.8203
Epoch 14/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5097 - accuracy: 0.8249
Epoch 15/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4371 - accuracy: 0.8221
Epoch 16/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3797 - accuracy: 0.8240
Epoch 17/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3094 - accuracy: 0.8230
Epoch 18/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2863 - accuracy: 0.8194
Epoch 19/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2565 - accuracy: 0.8230
Epoch 20/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6032 - accuracy: 0.8167
Epoch 21/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3037 - accuracy: 0.8240
Epoch 22/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0464 - accuracy: 0.8212
Epoch 23/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4488 - accuracy: 0.8221
Epoch 24/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0104 - accuracy: 0.8185
Epoch 25/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9370 - accuracy: 0.8221
Epoch 26/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9334 - accuracy: 0.8212
Epoch 27/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9668 - accuracy: 0.8212
Epoch 28/100
35/35 [==============================] - 0s 3ms/step - loss: 1.1055 - accuracy: 0.8258
Epoch 29/100
35/35 [==============================] - 0s 3ms/step - loss: 1.0266 - accuracy: 0.8194
Epoch 30/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2932 - accuracy: 0.8230
Epoch 31/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2015 - accuracy: 0.8185
Epoch 32/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1191 - accuracy: 0.8185
Epoch 33/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9532 - accuracy: 0.8230
Epoch 34/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9532 - accuracy: 0.8203
Epoch 35/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7672 - accuracy: 0.8230
Epoch 36/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8553 - accuracy: 0.8176
Epoch 37/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7654 - accuracy: 0.8212
Epoch 38/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1194 - accuracy: 0.8167
Epoch 39/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7105 - accuracy: 0.8185
Epoch 40/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7101 - accuracy: 0.8249
Epoch 41/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9377 - accuracy: 0.8267
Epoch 42/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8327 - accuracy: 0.8203
Epoch 43/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9042 - accuracy: 0.8185
Epoch 44/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7639 - accuracy: 0.8276
Epoch 45/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6603 - accuracy: 0.8176
Epoch 46/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7632 - accuracy: 0.8240
Epoch 47/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.8203
Epoch 48/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6564 - accuracy: 0.8249
Epoch 49/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6562 - accuracy: 0.8249
Epoch 50/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.8203
Epoch 51/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6876 - accuracy: 0.8212
Epoch 52/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5366 - accuracy: 0.8230
Epoch 53/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5610 - accuracy: 0.8249
Epoch 54/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6486 - accuracy: 0.8203
Epoch 55/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8825 - accuracy: 0.8230
Epoch 56/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5597 - accuracy: 0.8212
Epoch 57/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7746 - accuracy: 0.8203
Epoch 58/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7470 - accuracy: 0.8230
Epoch 59/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6005 - accuracy: 0.8240
Epoch 60/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5482 - accuracy: 0.8221
Epoch 61/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6302 - accuracy: 0.8249
Epoch 62/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7362 - accuracy: 0.8230
Epoch 63/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8281 - accuracy: 0.8203
Epoch 64/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8212 - accuracy: 0.8203
Epoch 65/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0805 - accuracy: 0.8276
Epoch 66/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5856 - accuracy: 0.8203
Epoch 67/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5582 - accuracy: 0.8221
Epoch 68/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5811 - accuracy: 0.8230
Epoch 69/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5451 - accuracy: 0.8258
Epoch 70/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7145 - accuracy: 0.8221
Epoch 71/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6656 - accuracy: 0.8221
Epoch 72/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6261 - accuracy: 0.8203
Epoch 73/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7592 - accuracy: 0.8240
Epoch 74/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7521 - accuracy: 0.8194
Epoch 75/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8462 - accuracy: 0.8249
Epoch 76/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5244 - accuracy: 0.8240
Epoch 77/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6044 - accuracy: 0.8212
Epoch 78/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5175 - accuracy: 0.8258
Epoch 79/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5151 - accuracy: 0.8230
Epoch 80/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5509 - accuracy: 0.8240
Epoch 81/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5241 - accuracy: 0.8249
Epoch 82/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5201 - accuracy: 0.8240
Epoch 83/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6594 - accuracy: 0.8230
Epoch 84/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5095 - accuracy: 0.8240
Epoch 85/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5428 - accuracy: 0.8212
Epoch 86/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6872 - accuracy: 0.8240
Epoch 87/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5661 - accuracy: 0.8276
Epoch 88/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5307 - accuracy: 0.8221
Epoch 89/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5420 - accuracy: 0.8258
Epoch 90/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5211 - accuracy: 0.8230
Epoch 91/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5622 - accuracy: 0.8267
Epoch 92/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6147 - accuracy: 0.8221
Epoch 93/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6541 - accuracy: 0.8212
Epoch 94/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7047 - accuracy: 0.8230
Epoch 95/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5629 - accuracy: 0.8240
Epoch 96/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5497 - accuracy: 0.8249
Epoch 97/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5882 - accuracy: 0.8240
Epoch 98/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5315 - accuracy: 0.8221
Epoch 99/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5164 - accuracy: 0.8212
Epoch 100/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6905 - accuracy: 0.8221

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.8960 - accuracy: 0.8723 - 189ms/epoch - 16ms/step
Loss: 0.895958423614502, Accuracy: 0.8722826242446899